import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
{ path: 'dashboard', loadComponent: () => import('./gestion-modeles-visuels-4/gestion-modeles-visuels-4.component').then(m => m.GestionModelesVisuels4Component) },
  { path: 'analyse-des-donnees-chercheur', loadComponent: () => import('./analyse-des-donnees-chercheur/analyse-des-donnees-chercheur.component').then(m => m.AnalyseDesDonneesChercheurComponent) },
  { path: 'catalogue-des-modeles-deployes', loadComponent: () => import('./catalogue-des-modeles-deployes/catalogue-des-modeles-deployes.component').then(m => m.CatalogueDesModelesDeployesComponent) },
  { path: 'configuration-indicateurs-rapport', loadComponent: () => import('./configuration-indicateurs-rapport/configuration-indicateurs-rapport.component').then(m => m.ConfigurationIndicateursRapportComponent) },
  { path: 'configuration-integration-dhis2', loadComponent: () => import('./configuration-integration-dhis2/configuration-integration-dhis2.component').then(m => m.ConfigurationIntegrationDhis2Component) },
  { path: 'configuration-modeles-risque', loadComponent: () => import('./configuration-modeles-risque/configuration-modeles-risque.component').then(m => m.ConfigurationModelesRisqueComponent) },
  { path: 'generateur-rapports-personnalises', loadComponent: () => import('./generateur-rapports-personnalises/generateur-rapports-personnalises.component').then(m => m.GenerateurRapportsPersonnalisesComponent) },
  { path: 'gestion-des-captures-laboratoire-5', loadComponent: () => import('./gestion-des-captures-laboratoire-5/gestion-des-captures-laboratoire-5.component').then(m => m.GestionDesCapturesLaboratoire5Component) },
  { path: 'gestion-des-datasets-et-annotations', loadComponent: () => import('./gestion-des-datasets-et-annotations/gestion-des-datasets-et-annotations.component').then(m => m.GestionDesDatasetsEtAnnotationsComponent) },
  { path: 'gestion-des-roles-et-permissions', loadComponent: () => import('./gestion-des-roles-et-permissions/gestion-des-roles-et-permissions.component').then(m => m.GestionDesRolesEtPermissionsComponent) },
  { path: 'gestion-des-sites-sentinelles-3', loadComponent: () => import('./gestion-des-sites-sentinelles-3/gestion-des-sites-sentinelles-3.component').then(m => m.GestionDesSitesSentinelles3Component) },
  { path: 'analyse-des-donnees-chercheur', loadComponent: () => import('./analyse-des-donnees-chercheur/analyse-des-donnees-chercheur.component').then(m => m.AnalyseDesDonneesChercheurComponent) },
  { path: 'catalogue-des-modeles-deployes', loadComponent: () => import('./catalogue-des-modeles-deployes/catalogue-des-modeles-deployes.component').then(m => m.CatalogueDesModelesDeployesComponent) },
  { path: 'configuration-indicateurs-rapport', loadComponent: () => import('./configuration-indicateurs-rapport/configuration-indicateurs-rapport.component').then(m => m.ConfigurationIndicateursRapportComponent) },
  { path: 'configuration-integration-dhis2', loadComponent: () => import('./configuration-integration-dhis2/configuration-integration-dhis2.component').then(m => m.ConfigurationIntegrationDhis2Component) },
  { path: 'configuration-modeles-risque', loadComponent: () => import('./configuration-modeles-risque/configuration-modeles-risque.component').then(m => m.ConfigurationModelesRisqueComponent) },
  { path: 'generateur-rapports-personnalises', loadComponent: () => import('./generateur-rapports-personnalises/generateur-rapports-personnalises.component').then(m => m.GenerateurRapportsPersonnalisesComponent) },
  { path: 'gestion-des-captures-laboratoire-5', loadComponent: () => import('./gestion-des-captures-laboratoire-5/gestion-des-captures-laboratoire-5.component').then(m => m.GestionDesCapturesLaboratoire5Component) },
  { path: 'gestion-des-datasets-et-annotations', loadComponent: () => import('./gestion-des-datasets-et-annotations/gestion-des-datasets-et-annotations.component').then(m => m.GestionDesDatasetsEtAnnotationsComponent) },
  { path: 'gestion-des-roles-et-permissions', loadComponent: () => import('./gestion-des-roles-et-permissions/gestion-des-roles-et-permissions.component').then(m => m.GestionDesRolesEtPermissionsComponent) },
  { path: 'gestion-des-sites-sentinelles-3', loadComponent: () => import('./gestion-des-sites-sentinelles-3/gestion-des-sites-sentinelles-3.component').then(m => m.GestionDesSitesSentinelles3Component) },
  { path: 'gestion-des-utilisateurs', loadComponent: () => import('./gestion-des-utilisateurs/gestion-des-utilisateurs.component').then(m => m.GestionDesUtilisateursComponent) },
  { path: 'gestion-donnees-hors-ligne', loadComponent: () => import('./gestion-donnees-hors-ligne/gestion-donnees-hors-ligne.component').then(m => m.GestionDonneesHorsLigneComponent) },
  { path: 'gestion-modeles-visuels-4', loadComponent: () => import('./gestion-modeles-visuels-4/gestion-modeles-visuels-4.component').then(m => m.GestionModelesVisuels4Component) },
  { path: 'parametres-de-synchronisation', loadComponent: () => import('./parametres-de-synchronisation/parametres-de-synchronisation.component').then(m => m.ParametresDeSynchronisationComponent) },
  { path: 'parametres-linguistiques', loadComponent: () => import('./parametres-linguistiques/parametres-linguistiques.component').then(m => m.ParametresLinguistiquesComponent) },
  { path: 'region-medicale-1', loadComponent: () => import('./region-medicale-1/region-medicale-1.component').then(m => m.RegionMedicale1Component) },
  { path: 'region-medicale-5', loadComponent: () => import('./region-medicale-5/region-medicale-5.component').then(m => m.RegionMedicale5Component) },
  { path: 'statut-synchronisation-globale', loadComponent: () => import('./statut-synchronisation-globale/statut-synchronisation-globale.component').then(m => m.StatutSynchronisationGlobaleComponent) },
  { path: 'surveillance-modeles-audio', loadComponent: () => import('./surveillance-modeles-audio/surveillance-modeles-audio.component').then(m => m.SurveillanceModelesAudioComponent) },
  { path: 'tableau-de-bord-activite-utilisateurs', loadComponent: () => import('./tableau-de-bord-activite-utilisateurs/tableau-de-bord-activite-utilisateurs.component').then(m => m.TableauDeBordActiviteUtilisateursComponent) },
  { path: 'tableau-de-bord-pipelines-ml-1', loadComponent: () => import('./tableau-de-bord-pipelines-ml-1/tableau-de-bord-pipelines-ml-1.component').then(m => m.TableauDeBordPipelinesMl1Component) },
  { path: 'tableau-de-bord-pipelines-ml-4', loadComponent: () => import('./tableau-de-bord-pipelines-ml-4/tableau-de-bord-pipelines-ml-4.component').then(m => m.TableauDeBordPipelinesMl4Component) },
  { path: 'tableau-de-bord-rapports-oms', loadComponent: () => import('./tableau-de-bord-rapports-oms/tableau-de-bord-rapports-oms.component').then(m => m.TableauDeBordRapportsOmsComponent) },
  { path: 'tableau-de-bord-synchro-dhis2', loadComponent: () => import('./tableau-de-bord-synchro-dhis2/tableau-de-bord-synchro-dhis2.component').then(m => m.TableauDeBordSynchroDhis2Component) },
  { path: 'validation-donnees-dhis2', loadComponent: () => import('./validation-donnees-dhis2/validation-donnees-dhis2.component').then(m => m.ValidationDonneesDhis2Component) },

  { path: '**', redirectTo: '/dashboard', pathMatch: 'full' }
];

